In [87]:
'''Q.1 Write a Python Program to Add Two Matrices'''

import numpy as np
def matrix_add(matrix1, matrix2):
    '''Add Two Matrices'''
    
    row = np.array(matrix1).shape[0]
    column = np.array(matrix1).shape[1]
    
    result = np.array([[0]*row]*column)
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            result[i][j] = matrix1[i][j] + matrix2[i][j]
    
    return np.array(result)

matrix1 = [[12,7,3],[4 ,5,6],[7 ,8,9]]
matrix2 = [[5,8,1],[6,7,3],[4,5,9]]


matrix_add(matrix1, matrix2)

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [82]:
'''Q.2 Write a Python Program to Multiply Two Matrices'''                              

import numpy as np
def matrix_matiplication(matrix1, matrix2):
    '''Multiply Two Matrices'''
    
    try:
        m1_row = np.array(matrix1).shape[0]
        m1_column = np.array(matrix1).shape[1]

        m2_row = np.array(matrix2).shape[0]
        m2_column = np.array(matrix2).shape[1]

        if m1_column == m2_row:
            matrix = np.array([[0]*m1_row]*m2_column)
            for i in range(len(matrix1)):
                for j in range(len(matrix2[0])):
                    for k in range(len(matrix2)):
                        matrix[i][j] += matrix1[i][k] * matrix2[k][j]
            
            return(np.array(matrix))

        else:
            print('Matrix 1 column not same on matrix 2 row')

    except IndexError:
        print('Matrix value input wrong')



matrix1 = [[1,2,3],[3,4,6],[1,2,5]]
matrix2 = [[5,6,4],[9,7,8],[1,2,3]]

matrix_matiplication(matrix1, matrix2)


array([[26, 26, 29],
       [57, 58, 62],
       [28, 30, 35]])

In [22]:
'''Q.3 Write a Python Program to Transpose a Matrix'''

import numpy as np
def matrix_transpose(matrix):
    '''Matrix Transpose'''
    
    matrix = np.array(matrix)
    row = matrix.shape[0]
    column = matrix.shape[1]
    result = np.array([[0]*row]*column)
    
    for j in range(len(matrix)):
        for i in range(len(matrix[0])):
            result[i][j] = matrix[j][i]
            
    return result

mat = [[1,2],[3,4],[6,7]]

matrix_transpose(mat)

array([[1, 3, 6],
       [2, 4, 7]])

In [60]:
'''Q.4 Write a Python Program to Sort Words in Alphabetic Order'''

def sort(str1):
    '''Sort word in alphabetic order'''
    res = ''
    for i in sorted(str1):
        res = res + i
    return res

str1 = 'Sougataineuron'
sort(str1)


'Saaeginnoortuu'

In [69]:
'''Q.5 Write a Python Program to Remove Punctuation From a String'''

def remove_punctuation(str1):
    '''Remove Punctuation from a string'''
    
    punctuation = '!?@#$%&'
    res = ''
    for i in str1:
        if i not in punctuation:
            res = res + i
            
    return res   
        
str1 = 'A boy! love?@ a girl $'
remove_punctuation(str1)

'A boy love a girl '